name: Build & publish wheels

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* *-musllinux_*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_ARCHS_WINDOWS: "AMD64"

          # 构建前安装依赖（在各平台的隔离环境中执行）
          CIBW_BEFORE_BUILD: >-
            python -m pip install -U pip pybind11 scikit-build-core ninja

          # 传给 scikit-build/CMake 的环境
          CIBW_ENVIRONMENT: >-
            CMAKE_GENERATOR=Ninja
            CMAKE_BUILD_PARALLEL_LEVEL=4

          # 轮子内自测（每个 Python 版本/平台跑一次）
          CIBW_TEST_COMMAND: >-
            python -c "import pybinparse as m; import array, mmap;
            b=array.array('B',[0]*40).tobytes();
            t=m.parse_line(b); print('OK',t[0]);"

        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Build sdist
        run: |
          python -m pip install -U build
          python -m build --sdist
          mkdir -p wheelhouse
          mv dist/*.tar.gz wheelhouse/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*

  publish:
    needs: build-wheels
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          packages-dir: dist
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true